# Generated by Django 3.0.7 on 2020-07-03 06:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('credit', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchant.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=32)),
                ('costumer_last_name', models.CharField(max_length=32)),
                ('order', models.CharField(max_length=128)),
                ('costumer_company', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 6, 38, 30, 999693, tzinfo=utc))),
                ('telephone_number', models.IntegerField()),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.UserProfile')),
            ],
        ),
    ]
