# Generated by Django 3.0.7 on 2020-07-03 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20200703_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 7, 3, 16, 187462, tzinfo=utc)),
        ),
    ]
