# Generated by Django 3.0.7 on 2020-07-06 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_auto_20200704_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 7, 45, 8, 906026, tzinfo=utc)),
        ),
    ]
