# Generated by Django 3.0.7 on 2020-07-06 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20200706_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 8, 20, 8, 47143, tzinfo=utc)),
        ),
    ]
