# Generated by Django 3.0.7 on 2020-07-06 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_auto_20200706_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 19, 6, 8, 240862, tzinfo=utc)),
        ),
    ]
